#import "../globals.typ": *

#context if text.lang == "de" [
    = Diskussion
    <sec:discussion>
] else [
    = Discussion
    <sec:discussion>
]

// 3-4 Seiten

== Anforderungen autonomer Orchestrierung

Die Ergebnisse zeigen, dass ein höherer Autonomiegrad in der untersuchten Konfiguration mit einer geringeren Ausführungsqualität und einem höheren Ressourcenbedarf verbunden ist. Die deterministische Methode erreicht über alle Aufgaben hinweg die höchsten Werte für Korrektheit und Effizienz, während die iterative Methode die niedrigsten Werte aufweist. Gleichzeitig steigen Laufzeit, Tokenverbrauch und Fehlerrate mit zunehmendem Autonomiegrad. Die Ergebnisse lassen sich damit als Trade-off zwischen zusätzlichem Entscheidungsspielraum und der Zuverlässigkeit sowie dem Ressourcenbedarf der Orchestrierung interpretieren.

Die differenzierte Betrachtung der Korrektheits- und Effizienzkomponenten zeigt, dass die Unterschiede zwischen den Methoden bereits bei der Toolauswahl deutlich werden. Die Werte für die korrekte Argumentübergabe liegen bei allen drei Methoden nur geringfügig unter den entsprechenden Werten der Toolauswahl. Dies deutet darauf hin, dass die Argumentübergabe im untersuchten Setup keinen wesentlich größeren zusätzlichen Fehlerbeitrag leistet. Die geringeren Gesamtwerte der autonomeren Methoden sind somit nicht primär auf eine deutlich schlechtere Argumentübergabe zurückzuführen, sondern zeigen sich bereits bei der Auswahl der benötigten Tools.

Die Betrachtung der Aufgabentypen zeigt darüber hinaus, dass die Auswirkungen des Autonomiegrads nicht für alle Aufgaben gleich ausfallen. Bei direkten Datenabfragen liegen die drei Methoden hinsichtlich Korrektheit und Effizienz vergleichsweise nah beieinander. Mit Aufgaben, bei denen mehrere Verarbeitungsschritte oder voneinander abhängige Toolergebnisse koordiniert werden müssen, verstärken sich die Unterschiede jedoch deutlich. Besonders bei der Mehrquellenverarbeitung erreicht die deterministische Methode weiterhin eine Korrektheit von 0,72, während die planbasierte und die iterative Methode nur 0,46 beziehungsweise 0,21 erreichen.

Diese Ergebnisse deuten darauf hin, dass insbesondere die Koordination voneinander abhängiger Verarbeitungsschritte eine erhöhte Anforderung an Orchestrierungsmethoden mit größerem Entscheidungsspielraum darstellt. Die autonomeren Verfahren müssen in solchen Fällen nicht nur geeignete Tools auswählen, sondern zusätzlich den bisherigen Zustand berücksichtigen, Verarbeitungsschritte aufeinander abstimmen und den weiteren Ablauf bestimmen. Gerade bei der iterativen Methode zeigte sich, dass diese zusätzlichen Entscheidungen zu fehlerhaften Toolaufrufen, redundanten Verarbeitungsschritten und Problemen bei der Verarbeitung vorheriger Ergebnisse führen können.

Aus den Ergebnissen folgt jedoch nicht, dass höhere Autonomie grundsätzlich ungeeignet ist. Die Untersuchung bewertet die zusätzliche Flexibilität nicht als eigene Metrik. Es kann daher nicht bestimmt werden, ob und unter welchen Bedingungen ein größerer Entscheidungsspielraum die beobachteten Einbußen rechtfertigt. Vielmehr zeigen die Ergebnisse, dass zusätzliche Autonomie in der untersuchten Konfiguration mit zusätzlichen Anforderungen verbunden ist und ihr Nutzen von den Eigenschaften der jeweiligen Aufgabe abhängen dürfte.

== Einfluss der Modelle

Neben dem Autonomiegrad zeigen auch die verwendeten Modelle deutliche Unterschiede. gpt-5.4-mini erreicht insgesamt die höchsten Korrektheits- und Effizienzwerte und weist als einziges der untersuchten Modelle keine erfassten Fehler auf. Die Ergebnisse erlauben jedoch keine allgemeine Aussage, dass größere Modelle grundsätzlich besser für die untersuchte Tool-Orchestrierung geeignet sind. Insbesondere qwen3:8b erreicht trotz geringerer Modellgröße höhere Korrektheits- und Effizienzwerte sowie eine niedrigere Fehlerrate als qwen3:30b.

Auch die kombinierte Betrachtung von Modell und Orchestrierungsmethode zeigt, dass die Auswirkungen des Autonomiegrads vom verwendeten Modell abhängen. Bei gpt-5.4-mini erreicht die deterministische Methode eine Korrektheit von 0,83 und liegt damit nur geringfügig vor der planbasierten Methode mit 0,79. Bei qwen3:30b ist der Unterschied mit 0,67 gegenüber 0,30 deutlich ausgeprägter. Bei qwen3:8b liegen die deterministische und die planbasierte Methode mit 0,66 beziehungsweise 0,67 dagegen nahezu gleichauf. Die Rangfolge der Methoden ist somit nicht vollständig modellunabhängig.

Gleichzeitig zeigt sich über alle drei Modelle hinweg ein konsistenter Nachteil der iterativen Methode hinsichtlich des Ressourcenbedarfs. Ihr Tokenverbrauch liegt bei jedem Modell über dem der deterministischen Methode. Besonders deutlich ist der Unterschied bei qwen3:8b, bei dem der durchschnittliche Verbrauch von 4.432 Tokens bei der deterministischen auf 12.149 Tokens bei der iterativen Methode steigt. Dies unterstützt die Beobachtung, dass die zusätzlichen Entscheidungsschritte der iterativen Orchestrierung mit einem erhöhten Ressourcenbedarf verbunden sind.

Der Modellvergleich ist jedoch ebenfalls im Kontext des konkreten Versuchsaufbaus zu betrachten. Die Modelle wurden unter unterschiedlichen technischen Ausführungsbedingungen eingesetzt, weshalb insbesondere absolute Laufzeiten zwischen den Modellen nur eingeschränkt vergleichbar sind. Zudem zeigte sich, dass die Modelle bereitgestellte Kontextinformationen unterschiedlich verarbeiteten. Beim API-basierten Modell wurde die vorgegebene Referenzzeit in mehreren Fällen nicht wie vorgesehen berücksichtigt, wodurch fehlerhafte Zeiträume in Toolargumenten entstanden. Der beobachtete Modellunterschied kann daher nicht ausschließlich als Unterschied in der allgemeinen Fähigkeit zur Tool-Orchestrierung interpretiert werden.

== Ressourcenbedarf und Fehleranfälligkeit

Die Ergebnisse bestätigen einen Zusammenhang zwischen dem Autonomiegrad und dem Ressourcenbedarf. Insbesondere der Tokenverbrauch zeigt ein konsistentes Muster über alle untersuchten Modelle hinweg. Die iterative Methode benötigt deutlich mehr Tokens als die deterministische und die planbasierte Methode. Dies lässt sich mit der Struktur der iterativen Orchestrierung in Verbindung bringen, bei der mehrere LLM-Aufrufe erforderlich sein können und der bisherige Zustand wiederholt verarbeitet werden muss.

Auch bei der Laufzeit zeigt sich ein erhöhter Aufwand autonomerer Verfahren. Besonders ausgeprägt ist dieser bei qwen3:8b und der iterativen Methode, die mit durchschnittlich 29,19 Sekunden deutlich über der deterministischen Methode desselben Modells mit 12,52 Sekunden liegt. Die absoluten Laufzeiten zwischen den verschiedenen Modellen sind aufgrund der unterschiedlichen technischen Ausführungsbedingungen jedoch nur eingeschränkt vergleichbar. Aussagekräftiger ist daher die Betrachtung der Methoden innerhalb desselben Modells.

Die Fehlerrate weist ebenfalls auf eine höhere Fehleranfälligkeit autonomerer Verfahren hin. Über alle Methoden steigt sie von 0,15 bei der deterministischen auf 0,29 bei der planbasierten und 0,31 bei der iterativen Methode. Der überwiegende Teil der beobachteten Fehler entfiel auf Timeouts. Zusätzlich trat über alle 810 Ausführungen lediglich ein Strukturfehler auf. Bei der iterativen Methode wurden darüber hinaus fehlerhafte Toolaufrufe beobachtet, beispielsweise durch die Verwendung nicht vorhandener Ergebnisreferenzen. Die Fehleranalyse zeigt damit, dass die erhöhte Fehlerrate nicht hauptsächlich durch strukturelle Probleme der technischen Infrastruktur verursacht wurde.

Gleichzeitig lässt sich aus den beobachteten Timeouts nicht ableiten, dass die höhere Anzahl an Iterationen unmittelbar deren Ursache ist. Ein Timeout kann unter anderem mit dem verwendeten Modell, der konkreten Aufgabe, den erforderlichen Verarbeitungsschritten oder den technischen Ausführungsbedingungen zusammenhängen. Die Ergebnisse zeigen daher eine erhöhte Fehleranfälligkeit autonomerer Verfahren, erlauben aber keine eindeutige kausale Zuordnung der Timeouts zu einem einzelnen Faktor.

== Bedeutung für Energiegemeinschaften und Limitationen

Für den Einsatz LLM-basierter Orchestrierungssysteme in Energiegemeinschaften sprechen die Ergebnisse insbesondere dann für einen deterministischeren Ansatz, wenn die erforderlichen Verarbeitungsschritte eindeutig spezifiziert werden können. Dies betrifft beispielsweise wiederkehrende Auswertungen, bei denen die benötigten Datenquellen und Verarbeitungsschritte bereits bekannt sind. In solchen Fällen zeigte die deterministische Methode im untersuchten Setup sowohl eine höhere Korrektheit und Effizienz als auch einen geringeren Ressourcenbedarf und eine niedrigere Fehlerrate.

Bei Aufgaben mit variablerem Ablauf kann ein größerer Entscheidungsspielraum grundsätzlich relevant sein, da nicht sämtliche möglichen Verarbeitungsschritte im Voraus festgelegt werden müssen. Die vorliegenden Ergebnisse zeigen jedoch keinen Vorteil autonomerer Verfahren bei den untersuchten Aufgaben mit mehreren voneinander abhängigen Verarbeitungsschritten. Insbesondere bei der Mehrquellenverarbeitung verstärkten sich die Unterschiede zwischen den Methoden deutlich. Daraus lässt sich ableiten, dass ein höherer Autonomiegrad nicht allein aufgrund der größeren Flexibilität als vorteilhaft angesehen werden sollte.

Die Aussagekraft der Ergebnisse ist durch mehrere Einschränkungen begrenzt. Untersucht wurden 90 Aufgaben, drei Aufgabentypen, drei Modelle und drei Orchestrierungsmethoden. Die Ergebnisse sind daher insbesondere als Evaluation der konkreten Kombination aus Aufgaben, Modellen, Prompts, Tools und Implementierungen zu verstehen. Die Aufgabentypen bilden dabei unterschiedliche Anforderungen an die Orchestrierung ab, stellen jedoch keine allgemeingültige Schwierigkeitsskala dar. Ebenso wurden keine wiederholten Ausführungen derselben Kombination aus Aufgabe, Modell und Methode durchgeführt, sodass die Ergebnisse nicht die vollständige stochastische Variabilität der Modelle erfassen.

Eine weitere Einschränkung besteht darin, dass die zusätzliche Flexibilität durch den höheren Autonomiegrad nicht direkt gemessen wurde. Die Untersuchung quantifiziert die damit verbundenen Unterschiede bei Korrektheit, Effizienz, Ressourcenbedarf und Fehlerrate, nicht jedoch den konkreten Nutzen des größeren Entscheidungsspielraums. Daher kann nicht bestimmt werden, ab welchem Grad an erforderlicher Ablaufvariabilität die zusätzlichen Kosten autonomerer Verfahren gerechtfertigt wären.

Insgesamt zeigen die Ergebnisse keinen grundsätzlichen Widerspruch zwischen höherer Autonomie und sinnvoller Tool-Orchestrierung. Sie verdeutlichen vielmehr, dass zusätzlicher Entscheidungsspielraum in der untersuchten Konfiguration mit höheren Anforderungen an die Entscheidungsfindung sowie mit messbaren Ressourcen- und Fehlerkosten verbunden ist. Gleichzeitig hängt die Auswirkung der gewählten Orchestrierungsmethode vom Aufgabentyp und vom verwendeten Modell ab. Für die Auswahl eines geeigneten Orchestrierungsansatzes ist daher nicht allein der erreichbare Autonomiegrad entscheidend, sondern dessen Verhältnis zu den konkreten Anforderungen der jeweiligen Aufgabe.